### ISSUE TITLE
This device tree can build CyanogenMod 12.1 for nx507j ?

### ISSUE THREAD

**Issue by pexcn** [ultimatum163/android_device_zte_nx507j#1]
or CyanogenMod 12.0 ?

**Comment by ultimatum163** [comment]
Cyanogenmod 12.1. I don't build dt.img will therefore edits

**Comment by pexcn** [comment]
@ultimatum163 Ok, I try to build Cyanogenmod 12.1, but I have a problem... (audio-caf moudle can't build pass...)
Can you push your kernel source and "local_manifests" to GitHub ? (Sorry, my bad English.)

**Comment by pexcn** [comment]
target thumb C: libqcompostprocbundle <= hardware/qcom/audio-caf/msm8974/post_proc/bundle.c
In file included from hardware/qcom/audio-caf/msm8974/post_proc/bundle.c:29:0:
hardware/qcom/audio-caf/msm8974/post_proc/bundle.h:24:33: fatal error: sound/audio_effects.h: No such file or directory
 #include <sound/audio_effects.h>
                                 ^
compilation terminated.
make: *** [/home/pexcn/pexcn/Android/source/nx507j/cm12.1/out/target/product/nx507j/obj/SHARED_LIBRARIES/libqcompostprocbundle_intermediates/bundle.o] Error 1

**Comment by ultimatum163** [comment]
edit kernel/sound/audio_effects.h
add patch https://gitlab.com/X9180/android_kernel_zte_x9180/commit/24efa7eb9edfc2e7f2e79ba847977e0fe761a0a0

**Comment by pexcn** [comment]
@ultimatum163 Thank you very much~~~

**Comment by pexcn** [comment]
@ultimatum163 Can you open all the source ? I want to build CyanogenMod 12.1 for me.

**Comment by ultimatum163** [comment]
I have not yet completed the kernel. When completed yet I lay out all the source code. yet he can not build cm 12.1

**Comment by pexcn** [comment]
Thank you~ :+1:  :)
